version: "3.7"

services:


  postgres-3:
    container_name: pg-3
    image: postgres:13.5
    environment:
      POSTGRES_DB: bdapro_database3
      POSTGRES_USER: bdapro_user
      POSTGRES_PASSWORD: bdapro_pwd
    restart: always
    healthcheck:
      test: pg_isready -U bdapro_user -d bdapro_pwd
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./COVID-19_Hospital_Capacity.csv:/var/lib/postgresql/csv_folder/COVID-19_Hospital_Capacity.csv:rw
      - ./Postgres_COVID-19_Hospital_Capacity.sql:/docker-entrypoint-initdb.d/Postgres_COVID-19_Hospital_Capacity.sql:rw
    ports:
      - 5432:5432


  postgres-1:
    container_name: pg-1
    image: postgres:13.5
    environment:
      POSTGRES_DB: bdapro_database1
      POSTGRES_USER: bdapro_user
      POSTGRES_PASSWORD: bdapro_pwd
    restart: always
    healthcheck:
      test: pg_isready -U bdapro_user -d bdapro_pwd
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./COVID-19_Hospital_Capacity.csv:/var/lib/postgresql/csv_folder/COVID-19_Hospital_Capacity.csv:rw
      - ./Postgres_COVID-19_Hospital_Capacity.sql:/docker-entrypoint-initdb.d/Postgres_COVID-19_Hospital_Capacity.sql:rw
    ports:
      - 8080:5432

  postgres-2:
    container_name: pg-2
    image: postgres:13.5
    environment:
      POSTGRES_DB: bdapro_database2
      POSTGRES_USER: bdapro_user
      POSTGRES_PASSWORD: bdapro_pwd
    restart: always
    healthcheck:
      test: pg_isready -U bdapro_user -d bdapro_pwd
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./COVID-19_Hospital_Capacity.csv:/var/lib/postgresql/csv_folder/COVID-19_Hospital_Capacity.csv:rw
      - ./Postgres_COVID-19_Hospital_Capacity.sql:/docker-entrypoint-initdb.d/Postgres_COVID-19_Hospital_Capacity.sql:rw
    ports:
      - 5432















#volumes:
#  volume-csv:
#    driver_opts:
#      type: local
#      o: bind
#      device: ./COVID-19_Hospital_Capacity.csv
#  volume-sql:
#    driver_opts:
#      type: local
#      o: bind
#      device: ./Postgres_COVID-19_Hospital_Capacity.sql
