version: "3.7"

services:

  maria-db-1:
    container_name: mdb-1
    #image: mariadb:10.5-focal
    image: mariadb-setup
    restart: always
    environment:
      MARIADB_DATABASE: bdapro_database
      MARIADB_USER: bdapro_user
      MARIADB_PASSWORD: bdapro_password
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - test-data:/docker-entrypoint-initdb.d/tpch:rw
      - ./mdb_create_tpch_sf1.sql:/docker-entrypoint-initdb.d/mdb_create_tpch_sf1.sql:rw
    ports:
      - 13306:3306
    networks:
      - bdapro_network

volumes:
  test-data:
    external: true

networks:
  bdapro_network:
    driver: bridge












#volumes:
#  volume-csv:
#    driver_opts:
#      type: local
#      o: bind
#      device: ./COVID-19_Hospital_Capacity.csv
#  volume-sql:
#    driver_opts:
#      type: local
#      o: bind
#      device: ./Postgres_COVID-19_Hospital_Capacity.sql
