version: "3.7"

services:

  postgres-1:
    container_name: pg-1
    image: postgres:13.5
    environment:
      POSTGRES_DB: bdapro_database
      POSTGRES_USER: bdapro_user
      POSTGRES_PASSWORD: bdapro_pwd
    restart: always
    healthcheck:
      test: pg_isready -U bdapro_user -d bdapro_pwd
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./COVID-19_Hospital_Capacity.csv:/var/lib/postgresql/csv_folder/COVID-19_Hospital_Capacity.csv:rw
      - ./Postgres_COVID-19_Hospital_Capacity.sql:/docker-entrypoint-initdb.d/Postgres_COVID-19_Hospital_Capacity.sql:rw
    ports:
      - 8080:5432

  postgres-2:
    container_name: pg-2
    image: postgres:13.5
    environment:
      POSTGRES_DB: bdapro_database
      POSTGRES_USER: bdapro_user
      POSTGRES_PASSWORD: bdapro_pwd
    restart: always
    healthcheck:
      test: pg_isready -U bdapro_user -d bdapro_pwd
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - ./COVID-19_Hospital_Capacity.csv:/var/lib/postgresql/csv_folder/COVID-19_Hospital_Capacity.csv:rw
      - ./Postgres_COVID-19_Hospital_Capacity.sql:/docker-entrypoint-initdb.d/Postgres_COVID-19_Hospital_Capacity.sql:rw
    ports:
      - 8081:5432


  maria-db-1:
    container_name: mdb-1
    image: mariadb:10.6
    restart: always
    environment:
      MARIADB_DATABASE: bdapro_database
      MARIADB_USER: bdapro_user
      MARIADB_PASSWORD: bdapro_password
      MARIADB_ROOT_PASSWORD: secret
    volumes:
      - ./COVID-19_Hospital_Capacity.csv:/docker-entrypoint-initdb.d/COVID-19_Hospital_Capacity.csv:rw
      - ./MariaDB_COVID-19_Hospital_Capacity.sql:/docker-entrypoint-initdb.d/MariaDB_COVID-19_Hospital_Capacity.sql:rw
















#volumes:
#  volume-csv:
#    driver_opts:
#      type: local
#      o: bind
#      device: ./COVID-19_Hospital_Capacity.csv
#  volume-sql:
#    driver_opts:
#      type: local
#      o: bind
#      device: ./Postgres_COVID-19_Hospital_Capacity.sql
