version: "3.7"

services:

  exasol:
    container_name: exa-1
    image: exasol/docker-db:latest
    privileged: true
#    volumes:
#      - ./COVID-19_Hospital_Capacity.csv:/var/lib/postgresql/csv_folder/COVID-19_Hospital_Capacity.csv:rw
#      - ./Postgres_COVID-19_Hospital_Capacity.sql:/docker-entrypoint-initdb.d/Postgres_COVID-19_Hospital_Capacity.sql:rw
    ports:
      - 8080:8563
#      - 8563:8574
#      - 2580:2591
#      - 8899:8888
#      - 8081:80
#      - 6932:6932
#      - 2580:2580
#      - 9563:8563
#      - 8899:8888
#      - 2580:2580
#      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3g
        reservations:
          cpus: '1'
          memory: 2g
