version: "3.7"

services:

  presto:
    container_name: presto_container
    image: presto
    ports:
      - 8084:8084
    networks:
      - docker_bdapro_network

networks:
  docker_bdapro_network:
    external: true